/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pakar.view;

/**
 *
 * @author X
 */
public class BentukPanel extends javax.swing.JPanel {

    /**
     * Creates new form BentukPanel
     */
    public BentukPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanelBentulColoumn = new javax.swing.JPanel();
        cbB1 = new javax.swing.JCheckBox();
        cbB2 = new javax.swing.JCheckBox();
        cbB3 = new javax.swing.JCheckBox();
        cbB4 = new javax.swing.JCheckBox();
        cbB5 = new javax.swing.JCheckBox();
        cbB6 = new javax.swing.JCheckBox();
        cbB7 = new javax.swing.JCheckBox();
        cbB8 = new javax.swing.JCheckBox();
        cbB9 = new javax.swing.JCheckBox();
        cbB10 = new javax.swing.JCheckBox();
        cbB11 = new javax.swing.JCheckBox();
        cbB12 = new javax.swing.JCheckBox();
        cbB13 = new javax.swing.JCheckBox();
        cbB14 = new javax.swing.JCheckBox();
        cbB15 = new javax.swing.JCheckBox();
        cbB16 = new javax.swing.JCheckBox();
        cbB17 = new javax.swing.JCheckBox();
        cbB18 = new javax.swing.JCheckBox();
        cbB19 = new javax.swing.JCheckBox();
        cbB20 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanelReliefColoumn = new javax.swing.JPanel();
        cbR1 = new javax.swing.JCheckBox();
        cbR2 = new javax.swing.JCheckBox();
        cbR3 = new javax.swing.JCheckBox();
        cbR4 = new javax.swing.JCheckBox();
        cbR5 = new javax.swing.JCheckBox();
        cbR6 = new javax.swing.JCheckBox();
        cbR7 = new javax.swing.JCheckBox();
        cbR8 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanelPleokorismeColoumn = new javax.swing.JPanel();
        cbP1 = new javax.swing.JCheckBox();
        cbP2 = new javax.swing.JCheckBox();
        cbP3 = new javax.swing.JCheckBox();
        cbP4 = new javax.swing.JCheckBox();
        cbP5 = new javax.swing.JCheckBox();
        cbP6 = new javax.swing.JCheckBox();
        cbP7 = new javax.swing.JCheckBox();
        cbP8 = new javax.swing.JCheckBox();
        cbP9 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        btnNext.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext);
        btnNext.setBounds(555, 438, 70, 31);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 438, 55, 31);

        jPanelBentulColoumn.setLayout(new java.awt.GridBagLayout());

        cbB1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB1.setText("Tabular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB1, gridBagConstraints);

        cbB2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB2.setText("Prismatik");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB2, gridBagConstraints);

        cbB3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB3.setText("Prismatik Panjang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB3, gridBagConstraints);

        cbB4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB4.setText("Prismatik Pendek");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB4, gridBagConstraints);

        cbB5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB5.setText("Euhedral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB5, gridBagConstraints);

        cbB6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB6.setText("Subhedral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB6, gridBagConstraints);

        cbB7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB7.setText("Anhedral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB7, gridBagConstraints);

        cbB8.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB8.setText("Granular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB8, gridBagConstraints);

        cbB9.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB9.setText("Lamelar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB9, gridBagConstraints);

        cbB10.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB10.setText("Fibrous");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB10, gridBagConstraints);

        cbB11.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB11.setText("Columnar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB11, gridBagConstraints);

        cbB12.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB12.setText("Pseudohexagonal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB12, gridBagConstraints);

        cbB13.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB13.setText("Hexagonal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB13, gridBagConstraints);

        cbB14.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB14.setText("Micaceous");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB14, gridBagConstraints);

        cbB15.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB15.setText("Scaly");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB15, gridBagConstraints);

        cbB16.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB16.setText("Fenokris");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB16, gridBagConstraints);

        cbB17.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB17.setText("Inklusi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB17, gridBagConstraints);

        cbB18.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB18.setText("Coarse Columnar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB18, gridBagConstraints);

        cbB19.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB19.setText("Agak Melengkung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB19, gridBagConstraints);

        cbB20.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbB20.setText("Vermicular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelBentulColoumn.add(cbB20, gridBagConstraints);

        add(jPanelBentulColoumn);
        jPanelBentulColoumn.setBounds(10, 70, 370, 280);

        jLabel1.setText("Bentuk");
        add(jLabel1);
        jLabel1.setBounds(120, 50, 50, 20);

        jPanelReliefColoumn.setLayout(new java.awt.GridBagLayout());

        cbR1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbR1.setText("Sangat tinggi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelReliefColoumn.add(cbR1, gridBagConstraints);

        cbR2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbR2.setText("Tinggi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelReliefColoumn.add(cbR2, gridBagConstraints);

        cbR3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbR3.setText("Tinggi menengah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelReliefColoumn.add(cbR3, gridBagConstraints);

        cbR4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbR4.setText("Agak tinggi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelReliefColoumn.add(cbR4, gridBagConstraints);

        cbR5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbR5.setText("Sedang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelReliefColoumn.add(cbR5, gridBagConstraints);

        cbR6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbR6.setText("Rendah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelReliefColoumn.add(cbR6, gridBagConstraints);

        cbR7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbR7.setText("Sangat rendah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelReliefColoumn.add(cbR7, gridBagConstraints);

        cbR8.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbR8.setText("Bervariasi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelReliefColoumn.add(cbR8, gridBagConstraints);

        add(jPanelReliefColoumn);
        jPanelReliefColoumn.setBounds(390, 70, 240, 220);

        jLabel2.setText("Relief");
        add(jLabel2);
        jLabel2.setBounds(490, 50, 50, 14);

        jPanelPleokorismeColoumn.setLayout(new java.awt.GridBagLayout());

        cbP1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP1.setText("Tidak Ada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP1, gridBagConstraints);

        cbP2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP2.setText("Lemah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP2, gridBagConstraints);

        cbP3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP3.setText("Lemah(kehijauan sampai kemerah-mudaan)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP3, gridBagConstraints);

        cbP4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP4.setText("Sedang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP4, gridBagConstraints);

        cbP5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP5.setText("Agak kuat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP5, gridBagConstraints);

        cbP6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP6.setText("Kuat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP6, gridBagConstraints);

        cbP7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP7.setText("Kuat(coklat muda ke coklat tua)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP7, gridBagConstraints);

        cbP8.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP8.setText("Kuat(hijau tua, hijau muda, kuning)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP8, gridBagConstraints);

        cbP9.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbP9.setText("Bervariasi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPleokorismeColoumn.add(cbP9, gridBagConstraints);

        add(jPanelPleokorismeColoumn);
        jPanelPleokorismeColoumn.setBounds(660, 80, 230, 230);

        jLabel3.setText("Pleokorisme");
        add(jLabel3);
        jLabel3.setBounds(750, 50, 80, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JCheckBox cbB1;
    private javax.swing.JCheckBox cbB10;
    private javax.swing.JCheckBox cbB11;
    private javax.swing.JCheckBox cbB12;
    private javax.swing.JCheckBox cbB13;
    private javax.swing.JCheckBox cbB14;
    private javax.swing.JCheckBox cbB15;
    private javax.swing.JCheckBox cbB16;
    private javax.swing.JCheckBox cbB17;
    private javax.swing.JCheckBox cbB18;
    private javax.swing.JCheckBox cbB19;
    private javax.swing.JCheckBox cbB2;
    private javax.swing.JCheckBox cbB20;
    private javax.swing.JCheckBox cbB3;
    private javax.swing.JCheckBox cbB4;
    private javax.swing.JCheckBox cbB5;
    private javax.swing.JCheckBox cbB6;
    private javax.swing.JCheckBox cbB7;
    private javax.swing.JCheckBox cbB8;
    private javax.swing.JCheckBox cbB9;
    private javax.swing.JCheckBox cbP1;
    private javax.swing.JCheckBox cbP2;
    private javax.swing.JCheckBox cbP3;
    private javax.swing.JCheckBox cbP4;
    private javax.swing.JCheckBox cbP5;
    private javax.swing.JCheckBox cbP6;
    private javax.swing.JCheckBox cbP7;
    private javax.swing.JCheckBox cbP8;
    private javax.swing.JCheckBox cbP9;
    private javax.swing.JCheckBox cbR1;
    private javax.swing.JCheckBox cbR2;
    private javax.swing.JCheckBox cbR3;
    private javax.swing.JCheckBox cbR4;
    private javax.swing.JCheckBox cbR5;
    private javax.swing.JCheckBox cbR6;
    private javax.swing.JCheckBox cbR7;
    private javax.swing.JCheckBox cbR8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelBentulColoumn;
    private javax.swing.JPanel jPanelPleokorismeColoumn;
    private javax.swing.JPanel jPanelReliefColoumn;
    // End of variables declaration//GEN-END:variables
}
