/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pakar.view;

/**
 *
 * @author X
 */
public class KembaranPanel extends javax.swing.JPanel {

    /**
     * Creates new form KembaranPanel
     */
    public KembaranPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rgroupIndeksBias = new javax.swing.ButtonGroup();
        rgroupOrientasiOptik = new javax.swing.ButtonGroup();
        rgroupSumbuOptik = new javax.swing.ButtonGroup();
        jPanelKembaran = new javax.swing.JPanel();
        cbK1 = new javax.swing.JCheckBox();
        cbK2 = new javax.swing.JCheckBox();
        cbK3 = new javax.swing.JCheckBox();
        cbK4 = new javax.swing.JCheckBox();
        cbK5 = new javax.swing.JCheckBox();
        cbK6 = new javax.swing.JCheckBox();
        cbK7 = new javax.swing.JCheckBox();
        cbK8 = new javax.swing.JCheckBox();
        cbK9 = new javax.swing.JCheckBox();
        cbK10 = new javax.swing.JCheckBox();
        cbK11 = new javax.swing.JCheckBox();
        cbK12 = new javax.swing.JCheckBox();
        cbK13 = new javax.swing.JCheckBox();
        cbK14 = new javax.swing.JCheckBox();
        cbK15 = new javax.swing.JCheckBox();
        cbK16 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanelIbOoSoTo = new javax.swing.JPanel();
        rbI1 = new javax.swing.JRadioButton();
        rbI2 = new javax.swing.JRadioButton();
        rbO1 = new javax.swing.JRadioButton();
        rbO2 = new javax.swing.JRadioButton();
        rbS1 = new javax.swing.JRadioButton();
        rbS2 = new javax.swing.JRadioButton();
        cbT1 = new javax.swing.JCheckBox();
        cbT2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        jPanelKembaran.setLayout(new java.awt.GridBagLayout());

        cbK1.setText("Kadang-kadang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK1, gridBagConstraints);

        cbK2.setText("Umum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK2, gridBagConstraints);

        cbK3.setText("Struktur herringbone ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK3, gridBagConstraints);

        cbK4.setText("Polisintetik");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK4, gridBagConstraints);

        cbK5.setText("Agak Umum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK5, gridBagConstraints);

        cbK6.setText("Albit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK6, gridBagConstraints);

        cbK7.setText("Kalsbad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK7, gridBagConstraints);

        cbK8.setText("Tidak ada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK8, gridBagConstraints);

        cbK9.setText("Tidak Umum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK9, gridBagConstraints);

        cbK10.setText("Periklin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK10, gridBagConstraints);

        cbK11.setText("Kembaran penetration dengan (110) sebagai bidang kembar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK11, gridBagConstraints);

        cbK12.setText("Kadang Melengkung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK12, gridBagConstraints);

        cbK13.setText("Polisintetik parallel dengan (221)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK13, gridBagConstraints);

        cbK14.setText("Dua individual ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK14, gridBagConstraints);

        cbK15.setText("Umum jarang terlihat ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK15, gridBagConstraints);

        cbK16.setText("Dua arah ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelKembaran.add(cbK16, gridBagConstraints);

        add(jPanelKembaran);
        jPanelKembaran.setBounds(10, 58, 470, 220);

        jLabel1.setText("Kembaran");
        add(jLabel1);
        jLabel1.setBounds(80, 40, 70, 14);

        jPanelIbOoSoTo.setLayout(new java.awt.GridBagLayout());

        rgroupIndeksBias.add(rbI1);
        rbI1.setText("n.mineral > n.k-balsam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelIbOoSoTo.add(rbI1, gridBagConstraints);

        rgroupIndeksBias.add(rbI2);
        rbI2.setText("n.mineral < n.k-balsam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelIbOoSoTo.add(rbI2, gridBagConstraints);

        rgroupOrientasiOptik.add(rbO1);
        rbO1.setText("Length Slow");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelIbOoSoTo.add(rbO1, gridBagConstraints);

        rgroupOrientasiOptik.add(rbO2);
        rbO2.setText("Length Fast");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelIbOoSoTo.add(rbO2, gridBagConstraints);

        rgroupSumbuOptik.add(rbS1);
        rbS1.setText("Satu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelIbOoSoTo.add(rbS1, gridBagConstraints);

        rgroupSumbuOptik.add(rbS2);
        rbS2.setText("Dua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelIbOoSoTo.add(rbS2, gridBagConstraints);

        cbT1.setText("Positif");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelIbOoSoTo.add(cbT1, gridBagConstraints);

        cbT2.setText("Negatif");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelIbOoSoTo.add(cbT2, gridBagConstraints);

        add(jPanelIbOoSoTo);
        jPanelIbOoSoTo.setBounds(120, 310, 320, 90);

        jLabel2.setText("Indeks Bias");
        add(jLabel2);
        jLabel2.setBounds(30, 320, 70, 14);

        jLabel3.setText("Orientasi Optik");
        add(jLabel3);
        jLabel3.setBounds(30, 340, 100, 14);

        jLabel4.setText("Sumbu Optik");
        add(jLabel4);
        jLabel4.setBounds(30, 360, 80, 14);

        jLabel5.setText("Tanda Optik");
        add(jLabel5);
        jLabel5.setBounds(30, 380, 80, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbK1;
    private javax.swing.JCheckBox cbK10;
    private javax.swing.JCheckBox cbK11;
    private javax.swing.JCheckBox cbK12;
    private javax.swing.JCheckBox cbK13;
    private javax.swing.JCheckBox cbK14;
    private javax.swing.JCheckBox cbK15;
    private javax.swing.JCheckBox cbK16;
    private javax.swing.JCheckBox cbK2;
    private javax.swing.JCheckBox cbK3;
    private javax.swing.JCheckBox cbK4;
    private javax.swing.JCheckBox cbK5;
    private javax.swing.JCheckBox cbK6;
    private javax.swing.JCheckBox cbK7;
    private javax.swing.JCheckBox cbK8;
    private javax.swing.JCheckBox cbK9;
    private javax.swing.JCheckBox cbT1;
    private javax.swing.JCheckBox cbT2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelIbOoSoTo;
    private javax.swing.JPanel jPanelKembaran;
    private javax.swing.JRadioButton rbI1;
    private javax.swing.JRadioButton rbI2;
    private javax.swing.JRadioButton rbO1;
    private javax.swing.JRadioButton rbO2;
    private javax.swing.JRadioButton rbS1;
    private javax.swing.JRadioButton rbS2;
    private javax.swing.ButtonGroup rgroupIndeksBias;
    private javax.swing.ButtonGroup rgroupOrientasiOptik;
    private javax.swing.ButtonGroup rgroupSumbuOptik;
    // End of variables declaration//GEN-END:variables
}
