/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pakar.view;

/**
 *
 * @author X
 */
public class WarnaPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarnaPanel
     */
    public WarnaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanelWColoumn = new javax.swing.JPanel();
        cbW1 = new javax.swing.JCheckBox();
        cbW2 = new javax.swing.JCheckBox();
        cbW3 = new javax.swing.JCheckBox();
        cbW4 = new javax.swing.JCheckBox();
        cbW5 = new javax.swing.JCheckBox();
        cbW6 = new javax.swing.JCheckBox();
        cbW7 = new javax.swing.JCheckBox();
        cbW8 = new javax.swing.JCheckBox();
        cbW9 = new javax.swing.JCheckBox();
        cbW10 = new javax.swing.JCheckBox();
        cbW11 = new javax.swing.JCheckBox();
        cbW12 = new javax.swing.JCheckBox();
        cbW13 = new javax.swing.JCheckBox();
        cbW14 = new javax.swing.JCheckBox();
        cbW15 = new javax.swing.JCheckBox();
        cbW16 = new javax.swing.JCheckBox();
        cbW33 = new javax.swing.JCheckBox();
        cbW17 = new javax.swing.JCheckBox();
        cbW18 = new javax.swing.JCheckBox();
        cbW19 = new javax.swing.JCheckBox();
        cbW20 = new javax.swing.JCheckBox();
        cbW21 = new javax.swing.JCheckBox();
        cbW22 = new javax.swing.JCheckBox();
        cbW23 = new javax.swing.JCheckBox();
        cbW24 = new javax.swing.JCheckBox();
        cbW25 = new javax.swing.JCheckBox();
        cbW26 = new javax.swing.JCheckBox();
        cbW27 = new javax.swing.JCheckBox();
        cbW28 = new javax.swing.JCheckBox();
        cbW29 = new javax.swing.JCheckBox();
        cbW30 = new javax.swing.JCheckBox();
        cbW31 = new javax.swing.JCheckBox();
        cbW32 = new javax.swing.JCheckBox();
        cbW34 = new javax.swing.JCheckBox();
        cbW35 = new javax.swing.JCheckBox();
        cbW36 = new javax.swing.JCheckBox();
        cbW37 = new javax.swing.JCheckBox();
        cbW38 = new javax.swing.JCheckBox();
        cbW39 = new javax.swing.JCheckBox();
        cbW40 = new javax.swing.JCheckBox();
        cbW41 = new javax.swing.JCheckBox();
        cbW42 = new javax.swing.JCheckBox();
        cbW43 = new javax.swing.JCheckBox();
        cbW44 = new javax.swing.JCheckBox();
        cbW45 = new javax.swing.JCheckBox();
        cbW46 = new javax.swing.JCheckBox();
        cbW47 = new javax.swing.JCheckBox();
        btnNext = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(680, 512));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        add(jPanel1);

        java.awt.GridBagLayout jPanelWColoumnLayout = new java.awt.GridBagLayout();
        jPanelWColoumnLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanelWColoumnLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanelWColoumn.setLayout(jPanelWColoumnLayout);

        cbW1.setText("Abu-abu kehijauan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW1, gridBagConstraints);

        cbW2.setText("Biru gelap kuning tua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW2, gridBagConstraints);

        cbW3.setText("Coklat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW3, gridBagConstraints);

        cbW4.setText("Coklat dan kuning");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW4, gridBagConstraints);

        cbW5.setText("Coklat kekuningan-coklat kemerahan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW5, gridBagConstraints);

        cbW6.setText("Coklat kehijau muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW6, gridBagConstraints);

        cbW7.setText("Coklat keunguan muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW7, gridBagConstraints);

        cbW8.setText("Coklat muda-tua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW8, gridBagConstraints);

        cbW9.setText("Dravite tidak berwarna sampai kuning");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW9, gridBagConstraints);

        cbW10.setText("Elbaite tidak berwarna");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW10, gridBagConstraints);

        cbW11.setText("Hampir tidak berwarna ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW11, gridBagConstraints);

        cbW12.setText("Hampir tidak netral ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW12, gridBagConstraints);

        cbW13.setText("Hijau");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW13, gridBagConstraints);

        cbW14.setText("Hijau,abu-abu kehijauan,sampai tidak berwarna");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW14, gridBagConstraints);

        cbW15.setText("Hijau zaitun ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW15, gridBagConstraints);

        cbW16.setText("Kehijauan ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW16, gridBagConstraints);

        cbW33.setText("Tidak berwarnasampai keruh, memperlihatkan deretan inklusi ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW33, gridBagConstraints);

        cbW17.setText("Kemerahan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW17, gridBagConstraints);

        cbW18.setText("Kemerahan muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW18, gridBagConstraints);

        cbW19.setText("Kuning");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW19, gridBagConstraints);

        cbW20.setText("Kuning kecoklatan ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW20, gridBagConstraints);

        cbW21.setText("Kuning muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW21, gridBagConstraints);

        cbW22.setText("Kuning sampai coklat (seringkali dengan batas opak)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW22, gridBagConstraints);

        cbW23.setText("Merah dan ungu ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW23, gridBagConstraints);

        cbW24.setText("Merah muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW24, gridBagConstraints);

        cbW25.setText("Netral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW25, gridBagConstraints);

        cbW26.setText("Netral - Hijau muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW26, gridBagConstraints);

        cbW27.setText("Oranye");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW27, gridBagConstraints);

        cbW28.setText("Abu-abu netral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW28, gridBagConstraints);

        cbW29.setText("Tidak Berwarna ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW29, gridBagConstraints);

        cbW30.setText("Tidak berwarna sampai abu-abu ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW30, gridBagConstraints);

        cbW31.setText("Tidak berwarna sampai biru muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW31, gridBagConstraints);

        cbW32.setText("Tidak berwarna sampai kehijauan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW32, gridBagConstraints);

        cbW34.setText("Tidak berwarna sampai kuning muda ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW34, gridBagConstraints);

        cbW35.setText("Tidak berwarna sampai hijau ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW35, gridBagConstraints);

        cbW36.setText("Tidak berwarna sampai hijau kekuningan ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW36, gridBagConstraints);

        cbW37.setText("Tidak berwarna sampai hijau muda ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW37, gridBagConstraints);

        cbW38.setText("Tidak berwarna sampai ungu muda ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW38, gridBagConstraints);

        cbW39.setText("Tidak berwarna seringkali terdiri dari inklusi ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW39, gridBagConstraints);

        cbW40.setText("Tidak berwarna seringkali berkabut ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW40, gridBagConstraints);

        cbW41.setText("Tidak berwarna tetapi berkabut");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW41, gridBagConstraints);

        cbW42.setText("Warna muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW42, gridBagConstraints);

        cbW43.setText("Zaitun");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW43, gridBagConstraints);

        cbW44.setText("Keunguan Muda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW44, gridBagConstraints);

        cbW45.setText("Tidak berwarna sampai hijau");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW45, gridBagConstraints);

        cbW46.setText("Struktur Zonasi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW46, gridBagConstraints);

        cbW47.setText("Tidak berwarna sampai kuning");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelWColoumn.add(cbW47, gridBagConstraints);

        add(jPanelWColoumn);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JCheckBox cbW1;
    private javax.swing.JCheckBox cbW10;
    private javax.swing.JCheckBox cbW11;
    private javax.swing.JCheckBox cbW12;
    private javax.swing.JCheckBox cbW13;
    private javax.swing.JCheckBox cbW14;
    private javax.swing.JCheckBox cbW15;
    private javax.swing.JCheckBox cbW16;
    private javax.swing.JCheckBox cbW17;
    private javax.swing.JCheckBox cbW18;
    private javax.swing.JCheckBox cbW19;
    private javax.swing.JCheckBox cbW2;
    private javax.swing.JCheckBox cbW20;
    private javax.swing.JCheckBox cbW21;
    private javax.swing.JCheckBox cbW22;
    private javax.swing.JCheckBox cbW23;
    private javax.swing.JCheckBox cbW24;
    private javax.swing.JCheckBox cbW25;
    private javax.swing.JCheckBox cbW26;
    private javax.swing.JCheckBox cbW27;
    private javax.swing.JCheckBox cbW28;
    private javax.swing.JCheckBox cbW29;
    private javax.swing.JCheckBox cbW3;
    private javax.swing.JCheckBox cbW30;
    private javax.swing.JCheckBox cbW31;
    private javax.swing.JCheckBox cbW32;
    private javax.swing.JCheckBox cbW33;
    private javax.swing.JCheckBox cbW34;
    private javax.swing.JCheckBox cbW35;
    private javax.swing.JCheckBox cbW36;
    private javax.swing.JCheckBox cbW37;
    private javax.swing.JCheckBox cbW38;
    private javax.swing.JCheckBox cbW39;
    private javax.swing.JCheckBox cbW4;
    private javax.swing.JCheckBox cbW40;
    private javax.swing.JCheckBox cbW41;
    private javax.swing.JCheckBox cbW42;
    private javax.swing.JCheckBox cbW43;
    private javax.swing.JCheckBox cbW44;
    private javax.swing.JCheckBox cbW45;
    private javax.swing.JCheckBox cbW46;
    private javax.swing.JCheckBox cbW47;
    private javax.swing.JCheckBox cbW5;
    private javax.swing.JCheckBox cbW6;
    private javax.swing.JCheckBox cbW7;
    private javax.swing.JCheckBox cbW8;
    private javax.swing.JCheckBox cbW9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelWColoumn;
    // End of variables declaration//GEN-END:variables
}
